In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))

32


In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [5]:
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
x = np.random.randn(10, 2)
h = np.dot(x, W1) + b1
h

array([[ 0.53677499,  1.41550964, -0.91716405,  1.1836723 ],
       [ 1.27198304, -2.19698577,  1.05429072, -1.66459798],
       [ 1.33997561, -2.37379315,  1.00719357, -1.7692823 ],
       [ 1.20235997, -0.88707985, -0.54412085, -0.41815917],
       [ 0.40851127,  1.3129494 , -0.19219542,  0.94104435],
       [ 0.79869016,  4.07411927, -5.97011357,  4.15083336],
       [ 0.73430612, -1.5401591 ,  2.50810988, -1.58493197],
       [-0.18061371,  3.98326285, -1.4446134 ,  2.9969169 ],
       [ 0.19823285,  4.96446042, -4.57529535,  4.398066  ],
       [ 0.43886932,  3.26732967, -3.17918199,  2.94633347]])

In [6]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [8]:
a = sigmoid(h)
a

array([[0.63106188, 0.80463351, 0.28553609, 0.76560745],
       [0.78108202, 0.1000215 , 0.74159798, 0.15914574],
       [0.79248593, 0.08519305, 0.73247057, 0.1456316 ],
       [0.76894434, 0.29171281, 0.36722949, 0.39695733],
       [0.60073086, 0.78800628, 0.45209851, 0.71931056],
       [0.68969422, 0.98327722, 0.00254745, 0.98449297],
       [0.67574951, 0.17651215, 0.9247084 , 0.17009813],
       [0.45496892, 0.98171577, 0.19083195, 0.95243465],
       [0.54939656, 0.99306669, 0.01019818, 0.98784837],
       [0.60798958, 0.96329086, 0.0399567 , 0.95008991]])

In [9]:
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)
s = np.dot(a, W2) + b2
s

array([[-1.09100666, -0.99157573, -2.01472865],
       [-1.86657922, -0.52220226, -2.44699481],
       [-1.86839787, -0.50700851, -2.40648886],
       [-1.46746329, -0.68760654, -1.65940199],
       [-1.22862257, -0.97241786, -2.44244946],
       [-0.72783404, -1.22621116, -1.40408728],
       [-1.98037819, -0.5182997 , -3.0491451 ],
       [-0.95701554, -1.08835468, -2.00927332],
       [-0.78903693, -1.12817573, -1.51151266],
       [-0.80915421, -1.12756513, -1.53405225]])